[package]
name = "SwapBytes"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.1", features = ["full"] }
async-trait = "0.1.81"
futures = "0.3.30"
clap = { version = "4.5.6", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
ratatui = { version = "0.28.1", features = ["widget-calendar"] }
itertools = "0.13.0"
unicode-width = "0.1.13"
color-eyre = "0.6.3"
crossterm = "0.28.1"
strum = "0.26.3"
palette = "0.7.6"
time = "0.3.36"
rand = "0.8.5"
rand_chacha = "0.3.1"
indoc = "2.0.5"
ratatui-widgets = "0.1.10"

[dependencies.libp2p]
version = "0.53.2"
features = ["tokio", "gossipsub", "noise", "macros", "tcp", "quic", "yamux", "rendezvous", "ping", "identify", "cbor", "request-response"]
