[package]
name = "SwapBytes"
version = "0.1.0"
edition = "2021"

[dependencies]
# chat application dependencies
# runtime for async applications
tokio = { version = "1.40.0", features = ["full"] }
# make async fn in traits work with dyn traits
async-trait = "0.1.81"
# futures and streams
futures = "0.3.30"
# allows easy logging style functionality with asynchronous programs
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

clap = { version = "4.5.6", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
ratatui = { version = "0.28.1", features = ["widget-calendar"] }
itertools = "0.13.0"
unicode-width = "0.1.13"
color-eyre = "0.6.3"
crossterm = "0.28.1"
strum = "0.26.3"
palette = "0.7.6"
time = "0.3.36"
rand = "0.8.5"
rand_chacha = "0.3.1"
indoc = "2.0.5"
ratatui-widgets = "0.1.10"
regex = "1.10.6"
serde_cbor = "0.11"
lazy_static = "1.4"

# libp2p
[dependencies.libp2p]
version = "0.54.1"
features = ["tokio", "gossipsub", "mdns", "noise", "macros", "tcp", "quic", "yamux", "rendezvous", "ping", "identify", "cbor", "request-response", "kad"]
